name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # запуск каждый день в полночь
  workflow_dispatch:      # возможность ручного запуска

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark